name: CI
on:
  push:
    branches: [master]
jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 10.x
          check-latest: true
      - name: Dependencies
        run: npx yarn install --frozen-lockfile
      - name: Build
        run: yarn dist
      - name: Import GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2.2.0
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ steps.import_gpg.outputs.keyid }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GIT_USERNAME: ${{ steps.import_gpg.outputs.name }}
          GIT_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
        run: yarn semantic-release
